# Generated by Django 6.0.2 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodocument',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/'),
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document')], default='pdf', max_length=10),
        ),
    ]
