# Generated by Django 6.0.2 on 2026-04-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0002_user_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
