# Generated by Django 6.0.2 on 2026-02-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0002_remove_audiodocument_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodocument',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('text', 'Plain Text')], default='pdf', max_length=10),
        ),
    ]
