# Generated by Django 6.0.2 on 2026-02-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0003_audiodocument_text_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodocument',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('text', 'Plain Text'), ('image', 'Image')], default='pdf', max_length=10),
        ),
    ]
