# Generated by Django 6.0.2 on 2026-04-30 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0003_user_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
