# Generated by Django 6.0.2 on 2026-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0004_audiodocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodocument',
            name='sentence_indices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
