# Generated by Django 6.0.2 on 2026-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0004_audiodocument_upload_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodocument',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('pending_payment', 'Pending Payment')], default='processing', max_length=20),
        ),
    ]
