# Generated by Django 6.0.2 on 2026-02-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0005_audiodocument_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodocument',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='audiodocument',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='audiodocument',
            name='payment_status',
        ),
    ]
