# Generated by Django 6.0.2 on 2026-05-07 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0005_audiodocument_sentence_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('mp3_file', models.FileField(blank=True, null=True, upload_to='uploads/chunks/')),
                ('word_timestamps', models.JSONField(default=list)),
                ('sentence_indices', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='readyaapp.audiodocument')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('document', 'index')},
            },
        ),
    ]
