# Generated by Django 6.0.2 on 2026-05-08 14:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0006_audiodocumentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodocumentchunk',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/chunks/'),
        ),
    ]
