# Generated by Django 6.0.2 on 2026-02-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0007_audiodocument_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodocument',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('pending_payment', 'Pending Payment')], default='pending_payment', max_length=20),
        ),
    ]
