# Generated by Django 6.0.2 on 2026-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0008_alter_audiodocument_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodocument',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='audiodocument',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='audiodocument',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('pending_payment', 'Pending Payment')], default='processing', max_length=20),
        ),
    ]
