# Generated by Django 6.0.2 on 2026-02-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0009_remove_audiodocument_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodocument',
            name='word_timestamps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
