# Generated by Django 6.0.2 on 2026-03-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readyaapp', '0012_temporaryuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporaryUser',
            new_name='User',
        ),
    ]
